### ISSUE TITLE
a request for a full example - nothing worked on JuliaPro 0.6.2.1

### ISSUE THREAD

**Issue by Alex0573** [JuliaDebug/ASTInterpreter2.jl#23]
I tried to run the debugger on Julia 0.6.2.1 but nothing seemed to work after 
"using ASTInterpreter2"
An example is most appreciated.

I tried:
- Running @enter issued "no function existed" error
- Running ASTInterpreter2.@enter issued another error - that I haven't set up the inv correctly (how do I do that?)
- all examples / code that use ASTInterpreter2 I could find online have @enter (which didn't work for me).

The only thing that did work, was the ASTInterpreter2.all_commands

ps - I'm running JuliaPro 0.6.2.1 on Mac.

Thanks a lot!

**Comment by Gnimuc** [comment]
what's your package status? It works fine with Julia0.6.2 on Mac, I never use JuliaPro, so hard to tell what's the problem.

```julia
julia> Pkg.status("ASTInterpreter2")
 - ASTInterpreter2               0.1.1

julia> @enter gcd(10)
In gcd(a) at intfuncs.jl:74
74  gcd(a::Integer) = a
75  lcm(a::Integer) = a
76  gcd(a::Integer, b::Integer) = gcd(promote(a,b)...)

About to run: return 10
1|debug > 
```

**Comment by Alex0573** [comment]
thanks @Gnimuc !
had the latest version but now restarted Julia and things work.
not sure what was the issue though

**Comment by Alex0573** [comment]
@Gnimuc can you provide an example with a breakpoint plz?
I want to run a function / code till a certain line number.
thanks!

**Comment by KristofferC** [comment]
Likely https://github.com/JuliaDebug/ASTInterpreter2.jl/pull/38
