### ISSUE TITLE
unknown function 

### ISSUE THREAD

**Issue by StevenCarte** [JuliaDebug/ASTInterpreter2.jl#50]
Debugger Function:

function func22()
    i = 10
    while i > 0
        println(sin(i))
        i -= 2
    end
end
@enter func22()

Exception: EXCEPTION_ACCESS_VIOLATION at 0x6697dfd3 -- ios_getc at /cygdrive/d/b
uildbot/worker/package_win64/build/src/support/cygdrive/d/buildbot/worker/packag
e_win64/build/src/support\ios.c:274
in expression starting at K:\PredictRockBost\src\test.jl:16
ios_getc at /cygdrive/d/buildbot/worker/package_win64/build/src/support/cygdrive
/d/buildbot/worker/package_win64/build/src/support\ios.c:274
jl_uncompress_ast at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdriv
e/d/buildbot/worker/package_win64/build/src\dump.c:2597
get_source at C:\Users\419-1\.julia\packages\ASTInterpreter2\DeeTn\src\ASTInterp
reter2.jl:319 [inlined]
#determine_method_for_expr#23 at C:\Users\419-1\.julia\packages\ASTInterpreter2\
DeeTn\src\ASTInterpreter2.jl:309
#determine_method_for_expr at .\none:0 [inlined]
#enter_call_expr#25 at C:\Users\419-1\.julia\packages\ASTInterpreter2\DeeTn\src\
ASTInterpreter2.jl:376
enter_call_expr at C:\Users\419-1\.julia\packages\ASTInterpreter2\DeeTn\src\ASTI
nterpreter2.jl:376
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/bui
ldbot/worker/package_win64/build/src\gf.c:2141 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive
/d/buildbot/worker/package_win64/build/src\gf.c:2305
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/build
bot/worker/package_win64/build/src\julia.h:1631 [inlined]
do_call at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildb
ot/worker/package_win64/build/src\interpreter.c:328
eval_value at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/bui
ldbot/worker/package_win64/build/src\interpreter.c:417
eval_stmt_value at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/
d/buildbot/worker/package_win64/build/src\interpreter.c:368 [inlined]
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buil
dbot/worker/package_win64/build/src\interpreter.c:764
jl_interpret_toplevel_thunk_callback at /cygdrive/d/buildbot/worker/package_win6
4/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:888

unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 000000001280C58F)
unknown function (ip: 0000000000000003)
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src/cyg
drive/d/buildbot/worker/package_win64/build/src\toplevel.c:814
jl_parse_eval_all at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdriv
e/d/buildbot/worker/package_win64/build/src\ast.c:873
jl_load at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildb
ot/worker/package_win64/build/src\toplevel.c:878 [inlined]
jl_load_ at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/build
bot/worker/package_win64/build/src\toplevel.c:885
include at .\boot.jl:328 [inlined]
include_relative at .\loading.jl:1105
include at .\Base.jl:31
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/bui
ldbot/worker/package_win64/build/src\gf.c:2135 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive
/d/buildbot/worker/package_win64/build/src\gf.c:2305
include at .\client.jl:424
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/bui
ldbot/worker/package_win64/build/src\gf.c:2135 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive
/d/buildbot/worker/package_win64/build/src\gf.c:2305
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/build
bot/worker/package_win64/build/src\julia.h:1631 [inlined]
do_call at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildb
ot/worker/package_win64/build/src\interpreter.c:328
eval_value at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/bui
ldbot/worker/package_win64/build/src\interpreter.c:417
eval_stmt_value at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/
d/buildbot/worker/package_win64/build/src\interpreter.c:368 [inlined]
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buil
dbot/worker/package_win64/build/src\interpreter.c:764
jl_interpret_toplevel_thunk_callback at /cygdrive/d/buildbot/worker/package_win6
4/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:888

unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 000000001280DA8F)
unknown function (ip: FFFFFFFFFFFFFFFF)
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src/cyg
drive/d/buildbot/worker/package_win64/build/src\toplevel.c:814
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src/cyg
drive/d/buildbot/worker/package_win64/build/src\toplevel.c:764
jl_toplevel_eval at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive
/d/buildbot/worker/package_win64/build/src\toplevel.c:823 [inlined]
jl_toplevel_eval_in at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdr
ive/d/buildbot/worker/package_win64/build/src\toplevel.c:843
eval at .\boot.jl:330
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/bui
ldbot/worker/package_win64/build/src\gf.c:2135 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive
/d/buildbot/worker/package_win64/build/src\gf.c:2305
eval_user_input at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib
\v1.3\REPL\src\REPL.jl:86
macro expansion at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib
\v1.3\REPL\src\REPL.jl:118 [inlined]
#26 at .\task.jl:333
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/bui
ldbot/worker/package_win64/build/src\gf.c:2135 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive
/d/buildbot/worker/package_win64/build/src\gf.c:2305
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/build
bot/worker/package_win64/build/src\julia.h:1631 [inlined]
start_task at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/bui
ldbot/worker/package_win64/build/src\task.c:659
Allocations: 839575 (Pool: 839302; Big: 273); GC: 1

**Comment by timholy** [comment]
As it says on the README (perhaps less forcefully than it should), don't use this package. See [Debugger.jl](https://github.com/JuliaDebug/Debugger.jl) or [Juno](https://docs.junolab.org/latest/), both of which use [JuliaInterpeter](https://github.com/JuliaDebug/JuliaInterpreter.jl).

**Comment by waldyrious** [comment]
@timholy shouldn't the repository be archived?
